name: CI / Build & Deploy to Azure VM

on:
  push:
    branches: [main, dev]

workflow_dispatch: 

env:
  IMAGE_NAME: nodejs-jenkins
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-jenkins:${{ github.sha }}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}
            ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}

  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ env.IMAGE }}
            docker stop nodejs-jenkins || true
            docker rm nodejs-jenkins || true
            docker run -d --name nodejs-jenkins -p 80:3000 ${{ env.IMAGE }}